export default{
    // Types of Media Center 
    GET_ALL_MEDIA_CENTER_REQUEST:'GET_ALL_MEDIA_CENTER_REQUEST:',
    GET_ALL_MEDIA_CENTER_SUCCESS:'GET_ALL_MEDIA_CENTER_SUCCESS',
    GET_ALL_MEDIA_CENTER_FAIL:'GET_ALL_MEDIA_CENTER_FAIL',
    SET_LOADING:'SET_LOADING',
}