export default {
    GET_NEWS_DETAIL_REQUEST:'GET_NEWS_DETAIL_REQUEST',
    GET_NEWS_DETAIL_SUCCESS:'GET_NEWS_DETAIL_SUCCESS',
    GET_NEWS_DETAIL_FAIL:'GET_NEWS_DETAIL_FAIL',
    SET_LOADING:'SET_LOADING'
}