//  Sector Projects
export default {
    GET_PROJECTS_REQUEST: "GET_PROJECTS_REQUEST",
    GET_PROJECTS_SUCCESS: "GET_PROJECTS_SUCCESS",
    GET_PROJECTS_FAIL: "GET_PROJECTS_FAIL",
    SET_LOADING: "SET_LOADING",
}