//  Sector Projects
export default {
    GET_PROJECT_DETAILS_REQUEST: "GET_PROJECT_DETAILS_REQUEST",
    GET_PROJECT_DETAILS_SUCCESS: "GET_PROJECT_DETAILS_SUCCESS",
    GET_PROJECT_DETAILS_FAIL: "GET_PROJECT_DETAILS_FAIL",
    SET_LOADING: "SET_LOADING",
}