export default{
    GET_ALL_SECTORS_REQUEST:'GET_ALL_SECTORS_REQUEST',
    GET_ALL_SECTORS_SUCCESS:'GET_ALL_SECTORS_SUCCESS',
    GET_ALL_SECTORS_FAIL:'GET_ALL_SECTORS_FAIL',
    SET_LOADING:'SET_LOADING',
}