// TYPES OF SECTOR DETAILS
export default{
    GET_SECTOR_DETAIL_REQUEST:"GET_SECTOR_DETAIL_REQUEST",
    GET_SECTOR_DETAIL_SUCCESS:"GET_SECTOR_DETAIL_SUCCESS",
    GET_SECTOR_DETAIL_FAIL:"GET_SECTOR_DETAIL_FAIL",
    SET_LOADING:"SET_LOADING",
}